const MESSAGE = {
  PLAY: "PLAY",
  PLAYED: "PLAYED",
  CONTINUE: "CONTINUE",
  STOP: "STOP",
  WINNED: "WINNED",
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  VALIDATE: "VALIDATE"
};

export default MESSAGE; 